parameters:
#    projet_l3_user.example.class: projetL3\UserBundle\Example

services:
#    projet_l3_user.example:
#        class: %projet_l3_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
